//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSpring.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ButtonInfo
    {
        public int Id { get; set; }
        public string ButtonName { get; set; }
        public string Icon { get; set; }
        public int Sort { get; set; }
        public System.DateTime AddDate { get; set; }
        public string HttpMethod { get; set; }
        public string ControllerFuncName { get; set; }
    }
}
